# HRHub HR Analytics Dataset Generator

This notebook generates a realistic Human Resource Analytics dataset for the **HRHub** project.

---

## 📌 Project Overview

This notebook creates a complete enterprise HR dataset from scratch using Python.

The generated dataset is designed for:

- HR Analytics Dashboard (Power BI)
- SQL Practice & Business Queries
- Excel Dashboard Development
- Python Data Analysis
- Machine Learning & Predictive Analytics
- HR KPI Reporting
- Portfolio & Interview Showcase

---

## 📂 Dataset to be Generated

The notebook will generate the following datasets:

- Employees
- Departments
- Calendar
- KPI Measures (Power BI)

---

## 📊 Key Features

- 2,500 Realistic Employees
- Logical Business Rules
- Dynamic Salary Structure
- Department-wise Distribution
- Experience-based Job Roles
- Attrition Probability Logic
- Performance Ratings
- Employee Demographics
- HR KPI Ready Data Model

---

## 🛠 Technologies Used

- Python
- Pandas
- NumPy
- Faker
- Random
- Datetime

---

## 🎯 Project Goal

Build a completely original HR Analytics dataset that can be used to create an executive-level Power BI dashboard with realistic business insights.

---

**Project Name:** HR Analytics Dashboard

**Prepared By:** Bijoy Mistry

**Version:** 1.0

**Status:** Development

In [ ]:
# ==========================================================
# HRHub HR Analytics Dataset Generator
# Author : Bijoy Mistry
# Project : HR Analytics Dashboard
# ==========================================================

!pip install Faker
import pandas as pd
import numpy as np
import random
from faker import Faker
import datetime

# Initialize Faker
fake = Faker("en_IN")

# Random Seed (for reproducible results)
random.seed(42)
np.random.seed(42)

print("Libraries Loaded Successfully")

Requirement already satisfied: Faker in /usr/local/lib/python3.12/dist-packages (40.32.0)
Libraries Loaded Successfully

## ⚙️ Project Configuration

This section defines the project parameters.

These values control:

- Number of Employees
- Company Name
- Date Range
- Random Seed
- Export Location

In [ ]:
# ==========================================================
# Project Configuration
# ==========================================================

TOTAL_EMPLOYEES = 2500

COMPANY_NAME = "HRHub"

START_DATE_STR = "2024-01-01"
END_DATE_STR   = "2028-12-31"

# Convert date strings to datetime objects
START_DATE = datetime.datetime.strptime(START_DATE_STR, "%Y-%m-%d")
END_DATE   = datetime.datetime.strptime(END_DATE_STR, "%Y-%m-%d")

CURRENT_YEAR = 2029

print("Project Configuration Loaded")

print(f"Company : {COMPANY_NAME}")
print(f"Employees : {TOTAL_EMPLOYEES}")
print(f"Date Range : {START_DATE.strftime('%Y-%m-%d')} to {END_DATE.strftime('%Y-%m-%d')}")

Project Configuration Loaded
Company : HRHub
Employees : 2500
Date Range : 2024-01-01 to 2028-12-31

# 📂 Master Lookup Lists

This section creates all master lookup tables used throughout the HR dataset.

These lookup values ensure:

- Consistent employee information
- Realistic HR data
- Standardized reporting
- Better Power BI relationships

In [ ]:
# ==========================================================
# MASTER LOOKUP LISTS
# ==========================================================

# Departments

departments = [
    "Administration",
    "Finance",
    "Human Resources",
    "IT",
    "Marketing",
    "Operations",
    "Sales"
]


# Job Roles

job_roles = [
    "HR Executive",
    "HR Manager",
    "Recruiter",
    "Software Engineer",
    "Senior Software Engineer",
    "System Administrator",
    "Network Engineer",
    "Data Analyst",
    "Finance Executive",
    "Accountant",
    "Marketing Executive",
    "Digital Marketing Specialist",
    "Sales Executive",
    "Sales Manager",
    "Operations Executive",
    "Operations Manager",
    "Administrative Officer"
]


# Gender

genders = [
    "Male",
    "Female"
]


# Marital Status

marital_status = [
    "Single",
    "Married",
    "Divorced"
]


# Education

education_levels = [
    "High School",
    "Diploma",
    "Bachelor",
    "Master",
    "MBA",
    "PhD"
]


# Business Travel

business_travel = [
    "Non-Travel",
    "Travel Rarely",
    "Travel Frequently"
]


# Overtime

overtime = [
    "Yes",
    "No"
]


# Work Mode

work_mode = [
    "Work From Office",
    "Hybrid",
    "Remote"
]


# Employment Status

employment_status = [
    "Active",
    "Resigned"
]


# Performance Rating

performance_rating = [
    1,
    2,
    3,
    4
]


# Job Satisfaction

job_satisfaction = [
    1,
    2,
    3,
    4
]


# Environment Satisfaction

environment_satisfaction = [
    1,
    2,
    3,
    4
]


# Work Life Balance

work_life_balance = [
    1,
    2,
    3,
    4
]


print("Master Lists Created Successfully")

Master Lists Created Successfully

# 🏢 Department & Job Role Mapping

Every department has specific job roles.

This mapping ensures employees are assigned only relevant positions.

For example:

- IT → Software Engineer, Data Analyst
- Finance → Accountant
- HR → Recruiter, HR Executive

This creates enterprise-grade realistic data.

In [ ]:
# ==========================================================
# DEPARTMENT -> JOB ROLE MAPPING
# ==========================================================

department_jobroles = {

    "Administration": [
        "Administrative Officer",
        "Office Executive",
        "Office Manager"
    ],

    "Finance": [
        "Finance Executive",
        "Senior Accountant",
        "Accountant",
        "Finance Manager"
    ],

    "Human Resources": [
        "HR Executive",
        "HR Manager",
        "Recruiter",
        "Talent Acquisition Specialist"
    ],

    "IT": [
        "Software Engineer",
        "Senior Software Engineer",
        "Data Analyst",
        "System Administrator",
        "Network Engineer",
        "Database Administrator"
    ],

    "Marketing": [
        "Marketing Executive",
        "Digital Marketing Specialist",
        "SEO Specialist",
        "Content Strategist",
        "Marketing Manager"
    ],

    "Operations": [
        "Operations Executive",
        "Operations Manager",
        "Supply Chain Executive",
        "Process Analyst"
    ],

    "Sales": [
        "Sales Executive",
        "Sales Manager",
        "Business Development Executive",
        "Key Account Manager"
    ]

}

print("Department Mapping Created")

Department Mapping Created

# 💰 Salary Structure

Each department follows its own salary band.

This improves the realism of:

- Salary Slab
- Attrition Analysis
- Average Salary
- Power BI KPIs

In [ ]:
# ==========================================================
# DEPARTMENT SALARY RANGE
# Annual Salary (INR)
# ==========================================================

salary_ranges = {

    "Administration": (300000, 900000),

    "Finance": (400000, 1400000),

    "Human Resources": (350000, 1200000),

    "IT": (500000, 2200000),

    "Marketing": (350000, 1500000),

    "Operations": (350000, 1400000),

    "Sales": (300000, 1800000)

}

print("Salary Ranges Created")

Salary Ranges Created

# 🧠 Business Rules

The following rules are used while generating employee records.

These rules ensure every employee has realistic and logically connected information.

Examples:

- Older employees generally have more experience.
- Salary depends on department.
- Attrition is higher for employees working overtime.
- Managers usually have higher salaries.
- Freshers rarely have 15+ years of experience.

In [ ]:
# ==========================================================
# BUSINESS RULE FUNCTIONS
# ==========================================================

def generate_age():

    return random.randint(18,60)


def age_group(age):

    if age <= 25:
        return "18-25"

    elif age <= 35:
        return "26-35"

    elif age <= 45:
        return "36-45"

    elif age <= 55:
        return "46-55"

    else:
        return "55+"


def generate_experience(age):

    max_exp = max(age-21,0)

    return random.randint(0,max_exp)


def salary_slab(salary):

    if salary < 300000:
        return "0-3 LPA"

    elif salary < 600000:
        return "3-6 LPA"

    elif salary < 1000000:
        return "6-10 LPA"

    else:
        return "10+ LPA"

In [ ]:
# ==========================================================
# ATTRITION BUSINESS RULE
# ==========================================================

def generate_attrition(overtime, job_satisfaction):

    probability = 0.08

    if overtime == "Yes":
        probability += 0.15

    if job_satisfaction <= 2:
        probability += 0.12

    if random.random() < probability:
        return "Yes"

    return "No"

In [ ]:
# ==========================================================
# EMPLOYEE STATUS
# ==========================================================

def employee_status(attrition):

    if attrition == "Yes":
        return "Resigned"

    return "Active"

In [ ]:
# ==========================================================
# SALARY HIKE %
# ==========================================================

def salary_hike():

    return random.randint(5,20)

In [ ]:
# ==========================================================
# PERFORMANCE RATING
# ==========================================================

def performance():

    return random.choices(

        [1,2,3,4],

        weights=[8,22,45,25]

    )[0]

In [ ]:
# ==========================================================
# JOB SATISFACTION
# ==========================================================

def satisfaction():

    return random.choices(

        [1,2,3,4],

        weights=[15,25,35,25]

    )[0]

# 👨‍💼 Employee Master Dataset Generation

This section generates all employee records using the business rules defined earlier.

Every employee receives:

- Unique Employee Code
- Personal Information
- HR Information
- Salary Information
- Employment Details
- Performance Metrics

The generated dataset closely resembles a real enterprise HRMS.

In [ ]:
# ==========================================================
# GENERATE EMPLOYEE MASTER DATASET
# ==========================================================

!pip install Faker # Added to ensure Faker is available for this cell
TOTAL_EMPLOYEES = 2500 # Added to resolve NameError
import random # Added to resolve NameError

genders = [
    "Male",
    "Female"
] # Added to resolve NameError

from faker import Faker # Added to resolve NameError for 'fake'
fake = Faker("en_IN") # Added to resolve NameError for 'fake'

employees = []

for i in range(1, TOTAL_EMPLOYEES + 1):

    employee_code = f"HR{100001+i}"

    gender = random.choice(genders)

    if gender == "Male":
        employee_name = fake.name_male()
    else:
        employee_name = fake.name_female()

    age = generate_age()

    agegroup = age_group(age)

    experience = generate_experience(age)

    department = random.choice(departments)

    jobrole = random.choice(department_jobroles[department])

    salary = random.randint(
        salary_ranges[department][0],
        salary_ranges[department][1]
    )

    salarieslab = salary_slab(salary)

    travel = random.choice(business_travel)

    workmode = random.choice(work_mode)

    overtime_status = random.choice(overtime)

    marital = random.choice(marital_status)

    education = random.choice(education_levels)

    jobsat = satisfaction()

    envsat = random.choice(environment_satisfaction)

    worklife = random.choice(work_life_balance)

    perf = performance()

    hike = salary_hike()

    attrition = generate_attrition(
        overtime_status,
        jobsat
    )

    status = employee_status(attrition)

    joining_date = fake.date_between(
        start_date=START_DATE,
        end_date=END_DATE
    )

    employees.append({

        "EmployeeCode": employee_code,

        "EmployeeName": employee_name,

        "Gender": gender,

        "Age": age,

        "AgeGroup": agegroup,

        "Department": department,

        "JobRole": jobrole,

        "AnnualSalary": salary,

        "SalarySlab": salarieslab,

        "Experience": experience,

        "JoiningDate": joining_date,

        "BusinessTravel": travel,

        "WorkMode": workmode,

        "OverTime": overtime_status,

        "MaritalStatus": marital,

        "Education": education,

        "JobSatisfaction": jobsat,

        "EnvironmentSatisfaction": envsat,

        "WorkLifeBalance": worklife,

        "PerformanceRating": perf,

        "SalaryHikePercent": hike,

        "Attrition": attrition,

        "EmploymentStatus": status

    })

print("Employee Dataset Generated Successfully")

Requirement already satisfied: Faker in /usr/local/lib/python3.12/dist-packages (40.32.0)
Employee Dataset Generated Successfully

In [ ]:
# ==========================================================
# CONVERT TO DATAFRAME
# ==========================================================

employees_df = pd.DataFrame(employees)

print(employees_df.shape)

employees_df.head()

(2500, 23)

,EmployeeCode,EmployeeName,Gender,Age,AgeGroup,Department,JobRole,AnnualSalary,SalarySlab,Experience,...,OverTime,MaritalStatus,Education,JobSatisfaction,EnvironmentSatisfaction,WorkLifeBalance,PerformanceRating,SalaryHikePercent,Attrition,EmploymentStatus
0,HR100002,Qasim Divan,Male,19,18-25,Finance,Senior Accountant,546316,3-6 LPA,0,...,Yes,Divorced,Master,1,1,2,2,5,No,Active
1,HR100003,Ekiya Chana,Female,32,26-35,Marketing,SEO Specialist,363628,3-6 LPA,7,...,No,Married,Bachelor,2,3,1,2,8,No,Active
2,HR100004,Janaki Brahmbhatt,Female,56,55+,Sales,Sales Executive,1263483,10+ LPA,16,...,No,Single,MBA,2,3,2,3,6,No,Active
3,HR100005,Indali Vohra,Female,23,18-25,Sales,Sales Executive,1097182,10+ LPA,0,...,No,Single,Bachelor,2,3,1,3,10,No,Active
4,HR100006,Ethan Chad,Male,28,26-35,IT,Data Analyst,1842176,10+ LPA,7,...,Yes,Divorced,Bachelor,4,1,2,4,15,No,Active

# 🌍 Enterprise Employee Details

Generate additional employee information that makes the dataset
look like it came from a real HR Management System (HRMS).

These fields improve dashboard quality and make the project
portfolio-ready.

In [ ]:
# ==========================================================
# LOCATION MASTER
# ==========================================================

states = [
    "Maharashtra",
    "Karnataka",
    "West Bengal",
    "Delhi",
    "Tamil Nadu",
    "Gujarat",
    "Telangana",
    "Uttar Pradesh",
    "Rajasthan",
    "Kerala"
]

cities = {
    "Maharashtra":["Mumbai","Pune","Nagpur"],
    "Karnataka":["Bengaluru","Mysuru","Hubli"],
    "West Bengal":["Kolkata","Howrah","Durgapur"],
    "Delhi":["New Delhi"],
    "Tamil Nadu":["Chennai","Coimbatore"],
    "Gujarat":["Ahmedabad","Surat"],
    "Telangana":["Hyderabad","Warangal"],
    "Uttar Pradesh":["Lucknow","Noida"],
    "Rajasthan":["Jaipur","Udaipur"],
    "Kerala":["Kochi","Trivandrum"]
}

print("Location Master Created")

Location Master Created

In [ ]:
def generate_email(name):

    username = (
        name.lower()
            .replace(" ",".")
            .replace("'","")
    )

    return username + "@hrhub.co.in"

In [ ]:
def generate_phone():

    return "9" + "".join(
        str(random.randint(0,9))
        for _ in range(9)
    )

In [ ]:
managers = {

"Administration":"Rahul Verma",

"Finance":"Anita Sharma",

"Human Resources":"Priya Singh",

"IT":"Amit Patel",

"Marketing":"Neha Kapoor",

"Operations":"Vikram Joshi",

"Sales":"Rohan Gupta"

}

DateOfBirth

State

City

Country

OfficialEmail

PhoneNumber

ManagerName

# 🏢 HRHub Company Profile

The generated dataset represents a fictional IT & Business Services company called **HRHub Solutions Pvt. Ltd.**

Company Details

• Company Name : HRHub Solutions Pvt. Ltd.

• Headquarters : Bengaluru, Karnataka

• Industry : Information Technology & Business Services

• Total Employees : 2500

• Countries : India

• Branch Offices : 10 States

• Departments : 7

This fictional company is used throughout the HR Analytics project to provide a realistic business scenario for dashboard development.

In [ ]:
# ==========================================================
# COMPANY MASTER
# ==========================================================

COMPANY = {

    "CompanyName":"HRHub Solutions Pvt. Ltd.",

    "Industry":"Information Technology & Business Services",

    "Country":"India",

    "HQ":"Bengaluru",

    "Currency":"INR",

    "WorkingDays":"Monday-Friday",

    "Shift":"General",

    "StandardHours":80

}

print("Company Master Created")

Company Master Created

In [ ]:
department_weights = {

    "IT":32,

    "Sales":22,

    "Operations":16,

    "Marketing":10,

    "Finance":8,

    "Human Resources":7,

    "Administration":5

}

In [ ]:
department_list = list(department_weights.keys())

department_probability = list(department_weights.values())

In [ ]:
department = random.choices(
    department_list,
    weights=department_probability,
    k=1
)[0]

In [ ]:
gender = random.choices(

    ["Male","Female"],

    weights=[64,36],

    k=1

)[0]

In [ ]:
marital = random.choices(

    ["Single","Married","Divorced"],

    weights=[42,53,5],

    k=1

)[0]

In [ ]:
workmode = random.choices(

    ["Work From Office","Hybrid","Remote"],

    weights=[48,37,15],

    k=1

)[0]

In [ ]:
travel = random.choices(

    ["Non-Travel",

     "Travel Rarely",

     "Travel Frequently"],

    weights=[28,56,16],

    k=1

)[0]

# 👤 Employee Identity Master

This section creates realistic employee identities.

Instead of generating completely random names, employees are
created using curated Indian first names and surnames.

Benefits

- Consistent employee identities
- Professional email addresses
- Realistic HR records
- Portfolio-quality dataset

In [ ]:
# ==========================================================
# FIRST NAMES
# ==========================================================

male_names = [

    "Aarav","Aditya","Akash","Amit","Ankit","Arjun","Ayush",
    "Deepak","Gaurav","Harsh","Karan","Manish","Mohit",
    "Nikhil","Pranav","Rahul","Raj","Rohan","Sahil",
    "Sandeep","Shubham","Sumit","Varun","Vikas","Vivek"

]

female_names = [

    "Aditi","Ananya","Anjali","Anusha","Deepika","Divya",
    "Harini","Ishita","Kavya","Khushi","Megha","Neha",
    "Nikita","Pooja","Priya","Riya","Ritika","Shreya",
    "Sneha","Sonali","Swati","Tanvi","Vaishnavi","Vidya"

]

In [ ]:
# ==========================================================
# LAST NAMES
# ==========================================================

last_names = [

    "Agarwal","Banerjee","Bose","Chatterjee","Das",
    "Ghosh","Gupta","Jain","Joshi","Kapoor","Khan",
    "Kumar","Mehta","Mishra","Mukherjee","Nair",
    "Patel","Rao","Reddy","Roy","Saha","Sen",
    "Shah","Sharma","Singh","Sinha","Verma"

]

In [ ]:
# ==========================================================
# GENERATE EMPLOYEE NAME
# ==========================================================

def generate_employee_name(gender):

    if gender == "Male":

        first = random.choice(male_names)

    else:

        first = random.choice(female_names)

    last = random.choice(last_names)

    return f"{first} {last}"

In [ ]:
# ==========================================================
# OFFICIAL EMAIL
# ==========================================================

def official_email(name):

    username = (
        name.lower()
            .replace(" ",".")
    )

    return username + "@hrhub.co.in"

In [ ]:
# ==========================================================
# USERNAME
# ==========================================================

def employee_username(name):

    return (
        name.lower()
            .replace(" ","")
            [:10]
    )

In [ ]:
department_managers = {

    "IT":"Amit Sharma",

    "Sales":"Rohan Gupta",

    "Finance":"Priya Nair",

    "Marketing":"Neha Kapoor",

    "Human Resources":"Anjali Singh",

    "Operations":"Vivek Mehta",

    "Administration":"Raj Verma"

}

In [ ]:
cities = {

    "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur"
    ],

    "Karnataka": [
        "Bengaluru",
        "Mysuru",
        "Hubballi"
    ],

    "West Bengal": [
        "Kolkata",
        "Howrah",
        "Durgapur"
    ],

    "Delhi": [
        "New Delhi"
    ],

    "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai"
    ],

    "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara"
    ],

    "Telangana": [
        "Hyderabad",
        "Warangal"
    ],

    "Uttar Pradesh": [
        "Lucknow",
        "Noida",
        "Kanpur"
    ],

    "Rajasthan": [
        "Jaipur",
        "Udaipur",
        "Jodhpur"
    ],

    "Kerala": [
        "Kochi",
        "Thiruvananthapuram",
        "Kozhikode"
    ]
}

Master Lists
      │
      ▼
Business Rules
      │
      ▼
Employee Generator
      │
      ▼
Validation
      │
      ▼
Export CSV

# 👨‍💼 Employee Generator

This function generates one employee record using all predefined
business rules and master lookup tables.

The final dataset is created by repeatedly calling this function.

Generate Identity
↓

Generate HR Details
↓

Generate Salary

↓

Generate Experience

↓

Generate Performance

↓

Generate Attrition

↓

Return Employee

hics

This section generates employee demographic information.

The generated fields include:

- Age
- Date of Birth
- Age Group
- Marital Status
- Education
- Education Field
- State
- City
- Phone Number

These fields are generated using business rules to maintain consistency across the dataset.

In [ ]:
# ==========================================================
# EDUCATION FIELDS
# ==========================================================

education_fields = {

    "High School":[
        "General Education"
    ],

    "Diploma":[
        "Mechanical",
        "Electrical",
        "Civil",
        "Computer"
    ],

    "Bachelor":[
        "Computer Science",
        "Information Technology",
        "Commerce",
        "Finance",
        "Marketing",
        "Human Resources",
        "Business Administration"
    ],

    "Master":[
        "Computer Science",
        "Finance",
        "Human Resources",
        "Marketing",
        "Business Administration"
    ],

    "MBA":[
        "Finance",
        "Marketing",
        "Human Resources",
        "Operations"
    ],

    "PhD":[
        "Computer Science",
        "Management",
        "Finance"
    ]
}

print("Education Fields Ready")

Education Fields Ready

In [ ]:
# ==========================================================
# DEPARTMENT & JOB ROLE MASTER
# ==========================================================

department_roles = {

    "Administration": [
        "Office Administrator",
        "Administrative Executive",
        "Facility Coordinator"
    ],

    "Finance": [
        "Accountant",
        "Financial Analyst",
        "Finance Executive"
    ],

    "Human Resources": [
        "HR Executive",
        "HR Business Partner",
        "Talent Acquisition Specialist"
    ],

    "IT": [
        "Software Engineer",
        "Data Analyst",
        "System Administrator",
        "Network Engineer"
    ],

    "Marketing": [
        "Marketing Executive",
        "Digital Marketing Specialist",
        "Content Strategist"
    ],

    "Operations": [
        "Operations Executive",
        "Operations Manager",
        "Supply Chain Coordinator"
    ],

    "Sales": [
        "Sales Executive",
        "Sales Manager",
        "Business Development Executive"
    ]
}

print("Department Master Ready")

Department Master Ready

In [ ]:
business_travel = [
    "Travel_Rarely",
    "Travel_Frequently",
    "Non-Travel"
]

work_modes = [
    "Work From Office",
    "Hybrid",
    "Remote"
]

In [ ]:
# This code was merged into the generate_employee function in cell GhhsuymygReM.
# employee["PhoneNumber"] = generate_phone()

# # ORGANIZATION
# department = random.choice(departments)

# employee["Department"] = department
# employee["JobRole"] = random.choice(department_roles[department])

# employee["BusinessTravel"] = random.choices(
#     business_travel,
#     weights=[60,20,20],
#     k=1
# )[0]

# employee["WorkMode"] = random.choices(
#     work_modes,
#     weights=[65,25,10],
#     k=1
# )[0]

# return employee

In [ ]:
# ==========================================================
# JOB LEVELS
# ==========================================================

job_levels = [1,2,3,4,5]

job_level_weights = [30,30,20,15,5]


salary_ranges = {

    1:(25000,45000),

    2:(40000,70000),

    3:(65000,100000),

    4:(95000,150000),

    5:(145000,250000)

}

print("Job Level Master Ready")

Job Level Master Ready

In [ ]:
# ==========================================================
# EXPERIENCE FUNCTIONS
# ==========================================================

def hire_date_from_experience(exp):

    today = datetime.date(CURRENT_YEAR,1,1)

    days = int(exp*365)

    return today - datetime.timedelta(days=days)


def salary_slab(monthly_salary):

    annual = monthly_salary*12

    if annual < 300000:
        return "0-3 LPA"

    elif annual < 600000:
        return "3-6 LPA"

    elif annual < 1000000:
        return "6-10 LPA"

    else:
        return "10+ LPA"

print("Experience Functions Ready")

Experience Functions Ready

In [ ]:
print(datetime)

<module 'datetime' from '/usr/lib/python3.12/datetime.py'>

In [ ]:
# ==========================================================
# DATE OF BIRTH FUNCTION
# ==========================================================

def dob_from_age(age):

    today = datetime.datetime.today()

    dob = today - datetime.timedelta(days=365 * age)

    return dob.date()


print("DOB Function Ready")

DOB Function Ready

In [ ]:
# ==========================================================
# ATTRITION ENGINE
# ==========================================================

def calculate_attrition(employee):

    score = 0

    # Younger employees leave more often
    if employee["Age"] < 30:
        score += 2

    # Low satisfaction
    if employee["JobSatisfaction"] <= 2:
        score += 3

    # Poor work-life balance
    if employee["WorkLifeBalance"] <= 2:
        score += 2

    # Frequent travel
    if employee["BusinessTravel"] == "Travel_Frequently":
        score += 2

    # Overtime
    if employee["OverTime"] == "Yes":
        score += 2

    # Low experience
    if employee["YearsAtCompany"] <= 2:
        score += 2

    # Low salary
    if employee["SalarySlab"] == "0-3 LPA":
        score += 2

    probability = min(score / 30, 0.18)

    return "Yes" if random.random() < probability else "No"


print("Attrition Engine Ready")

Attrition Engine Ready

In [ ]:
# ==========================================================
# COMPANY TENURE FUNCTIONS
# ==========================================================

def years_at_company(total_exp):
    return random.randint(0, max(0, int(total_exp)))

def years_current_role(years_company):
    return random.randint(0, max(0, int(years_company)))

def years_since_promotion(years_company):
    return random.randint(0, max(0, int(years_company // 2)))

def years_with_manager(years_company):
    return random.randint(0, max(0, int(years_company)))

print("Company Tenure Functions Ready")

Company Tenure Functions Ready

In [ ]:
# ==========================================================
# BUSINESS LOGIC FUNCTIONS
# ==========================================================

# -------------------------------
# EXPERIENCE
# -------------------------------

def generate_experience(age):

    max_exp = max(age - 21, 0)

    return round(random.uniform(0, max_exp), 1)


# -------------------------------
# TENURE
# -------------------------------

def years_at_company(total_exp):

    return random.randint(0, max(0, int(total_exp)))


def years_current_role(years_company):

    return random.randint(0, max(0, years_company))


def years_since_promotion(years_company):

    return random.randint(0, max(0, years_company // 2))


def years_with_manager(years_company):

    return random.randint(0, max(0, years_company))


# -------------------------------
# SALARY
# -------------------------------

salary_ranges = {

    "Administrative Executive": (18000,30000),
    "HR Executive": (22000,35000),
    "Recruiter": (22000,32000),
    "Payroll Executive": (25000,38000),

    "Sales Executive": (22000,45000),
    "Sales Manager": (50000,90000),

    "Software Engineer": (35000,70000),
    "Senior Software Engineer": (65000,110000),
    "Data Analyst": (35000,65000),
    "Data Scientist": (70000,120000),
    "Network Engineer": (35000,70000),

    "Finance Executive": (30000,55000),
    "Accountant": (28000,50000),

    "Marketing Executive": (28000,50000),
    "Digital Marketing Specialist": (35000,65000),

    "Operations Executive": (28000,50000),
    "Operations Manager": (60000,100000),

    "Manager": (80000,140000)
}

def generate_salary(department, jobrole, experience):

    # Base salary mainly depends on experience
    if experience < 2:
        salary = random.randint(18000, 32000)

    elif experience < 5:
        salary = random.randint(32000, 50000)

    elif experience < 10:
        salary = random.randint(50000, 80000)

    elif experience < 15:
        salary = random.randint(80000, 120000)

    else:
        salary = random.randint(120000, 180000)

    # Department adjustment
    if department == "IT":
        salary += random.randint(5000, 15000)

    elif department == "Finance":
        salary += random.randint(5000, 12000)

    elif department == "Sales":
        salary += random.randint(3000, 10000)

    elif department == "Marketing":
        salary += random.randint(3000, 8000)

    elif department == "Operations":
        salary += random.randint(2000, 7000)

    elif department == "Human Resources":
        salary += random.randint(1000, 5000)

    # Manager roles
    if "Manager" in jobrole:
        salary += random.randint(30000, 60000)

    # Round to nearest ₹50
    salary = int(round(salary / 50) * 50)

    return salary

print("Business Logic Functions Ready")

Business Logic Functions Ready

In [ ]:
# ==========================================================
# EMPLOYEE GENERATOR
# ==========================================================

def generate_employee(emp_no):

    employee = {}

    # ======================================================
    # EMPLOYEE IDENTITY
    # ======================================================

    employee["EmployeeCode"] = f"HRA{240000 + emp_no:05d}"

    gender = random.choice(["Male","Female"])

    employee["Gender"] = gender

    employee["EmployeeName"] = generate_employee_name(gender)

    username = (
        employee["EmployeeName"]
        .lower()
        .replace(" ",".")
    )

    employee["OfficialEmail"] = username + "@hrhub.co.in"

    employee["Username"] = username

    # ======================================================
    # COMPANY DETAILS
    # ======================================================

    employee["EmployeeCount"] = 1

    employee["Over18"] = "Y"

    employee["StandardHours"] = 80

    employee["Company"] = COMPANY["CompanyName"]

    employee["Industry"] = COMPANY["Industry"]

    employee["Country"] = COMPANY["Country"]

# ======================================================
# DEMOGRAPHICS
# ======================================================

    age = generate_age()

    employee["Age"] = age

    employee["AgeGroup"] = age_group(age)

    employee["DateOfBirth"] = dob_from_age(age)

    employee["MaritalStatus"] = random.choices(
        ["Single", "Married", "Divorced"],
        weights=[42, 53, 5],
        k=1
)[0]

    education = random.choice(education_levels)

    employee["Education"] = education

    employee["EducationField"] = random.choice(
        education_fields[education]
)

    state = random.choice(states)

    employee["State"] = state

    employee["City"] = random.choice(
        cities[state]
)

    employee["PhoneNumber"] = generate_phone()

# ======================================================
# ORGANIZATION
# ======================================================

    department = random.choice(departments)

    employee["Department"] = department

    employee["JobRole"] = random.choice(
    department_roles[department]
)

    employee["BusinessTravel"] = random.choices(
        business_travel,
        weights=[60, 20, 20],
        k=1
)[0]

    employee["WorkMode"] = random.choices(
        work_modes,
        weights=[65, 25, 10],
        k=1
)[0]

# ======================================================
# EXPERIENCE
# ======================================================

    experience = generate_experience(employee["Age"])

    employee["TotalWorkingYears"] = experience

    employee["YearsAtCompany"] = years_at_company(experience)

    employee["YearsInCurrentRole"] = years_current_role(
        employee["YearsAtCompany"]
)

    employee["YearsSinceLastPromotion"] = years_since_promotion(
        employee["YearsAtCompany"]
)

    employee["YearsWithCurrManager"] = years_with_manager(
        employee["YearsAtCompany"]
)

    employee["HireDate"] = hire_date_from_experience(experience)

# ======================================================
# SALARY
# ======================================================

    salary = generate_salary(
        employee["Department"],
        employee["JobRole"],
        employee["TotalWorkingYears"]
)

    employee["MonthlyIncome"] = salary

    employee["SalarySlab"] = salary_slab(salary)

    employee["SalaryHikePercent"] = random.randint(5, 25)

    employee["StockOptionLevel"] = random.randint(0, 3)

# ======================================================
# PERFORMANCE & SATISFACTION
# ======================================================

    employee["PerformanceRating"] = random.choices(
        [1, 2, 3, 4],
        weights=[5, 15, 60, 20],
        k=1
)[0]

    employee["JobSatisfaction"] = random.randint(1, 4)

    employee["EnvironmentSatisfaction"] = random.randint(1, 4)

    employee["RelationshipSatisfaction"] = random.randint(1, 4)

    employee["WorkLifeBalance"] = random.randint(1, 4)

    employee["TrainingTimesLastYear"] = random.randint(0, 6)

    employee["NumCompaniesWorked"] = min(
        random.randint(0, 10),
        employee["TotalWorkingYears"]
)

# ======================================================
# PROMOTION
# ======================================================

    employee["PromotionLast5Years"] = random.choices(
        ["Yes", "No"],
        weights=[18, 82],
        k=1
)[0]

# ======================================================
# OVERTIME
# ======================================================

    employee["OverTime"] = random.choices(
        ["Yes", "No"],
        weights=[28, 72],
        k=1
)[0]

# ======================================================
# ATTRITION
# ======================================================

    employee["Attrition"] = calculate_attrition(employee)

    return employee

print("Employee Generator Created Successfully")

Employee Generator Created Successfully

In [ ]:
emp = generate_employee(1)

emp

{'EmployeeCode': 'HRA240001',
 'Gender': 'Male',
 'EmployeeName': 'Rohan Mehta',
 'OfficialEmail': 'rohan.mehta@hrhub.co.in',
 'Username': 'rohan.mehta',
 'EmployeeCount': 1,
 'Over18': 'Y',
 'StandardHours': 80,
 'Company': 'HRHub Solutions Pvt. Ltd.',
 'Industry': 'Information Technology & Business Services',
 'Country': 'India',
 'Age': 52,
 'AgeGroup': '46-55',
 'DateOfBirth': datetime.date(1974, 8, 3),
 'MaritalStatus': 'Married',
 'Education': 'Bachelor',
 'EducationField': 'Commerce',
 'State': 'Karnataka',
 'City': 'Bengaluru',
 'PhoneNumber': '9359989625',
 'Department': 'Marketing',
 'JobRole': 'Digital Marketing Specialist',
 'BusinessTravel': 'Travel_Rarely',
 'WorkMode': 'Hybrid',
 'TotalWorkingYears': 7.6,
 'YearsAtCompany': 6,
 'YearsInCurrentRole': 0,
 'YearsSinceLastPromotion': 0,
 'YearsWithCurrManager': 3,
 'HireDate': datetime.date(2021, 5, 29),
 'MonthlyIncome': 75750,
 'SalarySlab': '6-10 LPA',
 'SalaryHikePercent': 15,
 'StockOptionLevel': 2,
 'PerformanceRating': 2,
 'JobSatisfaction': 1,
 'EnvironmentSatisfaction': 4,
 'RelationshipSatisfaction': 4,
 'WorkLifeBalance': 3,
 'TrainingTimesLastYear': 0,
 'NumCompaniesWorked': 7.6,
 'PromotionLast5Years': 'No',
 'OverTime': 'No',
 'Attrition': 'No'}

In [ ]:
# ==========================================================
# GENERATE COMPLETE DATASET
# ==========================================================

employees = []

for emp_no in range(1, TOTAL_EMPLOYEES + 1):
    employees.append(generate_employee(emp_no))

print(f"{len(employees)} employee records generated successfully.")

2500 employee records generated successfully.

In [ ]:
# ==========================================================
# CREATE DATAFRAME
# ==========================================================

employee_df = pd.DataFrame(employees)

print(employee_df.shape)

employee_df.head()

(2500, 44)

,EmployeeCode,Gender,EmployeeName,OfficialEmail,Username,EmployeeCount,Over18,StandardHours,Company,Industry,...,PerformanceRating,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,TrainingTimesLastYear,NumCompaniesWorked,PromotionLast5Years,OverTime,Attrition
0,HRA240001,Female,Harini Bose,harini.bose@hrhub.co.in,harini.bose,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,4,2,3,4,1,5,5.5,No,No,Yes
1,HRA240002,Female,Ritika Shah,ritika.shah@hrhub.co.in,ritika.shah,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,1,1,1,3,1,2,2.6,No,No,No
2,HRA240003,Female,Aditi Gupta,aditi.gupta@hrhub.co.in,aditi.gupta,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,4,1,2,3,4,3,6.0,No,Yes,Yes
3,HRA240004,Female,Sneha Patel,sneha.patel@hrhub.co.in,sneha.patel,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,3,4,3,4,1,1,0.0,No,No,No
4,HRA240005,Male,Harsh Jain,harsh.jain@hrhub.co.in,harsh.jain,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,2,2,3,3,4,2,0.7,No,Yes,No

In [ ]:
# ==========================================================
# DATASET VALIDATION
# ==========================================================

print("="*60)
print("HR DATASET VALIDATION")
print("="*60)

print(f"\nTotal Employees : {len(employee_df)}")

print(f"Total Columns   : {employee_df.shape[1]}")

print("\nDuplicate Employee Codes :", employee_df["EmployeeCode"].duplicated().sum())

print("Missing Values :")
print(employee_df.isnull().sum().sum())

print("\nGender Distribution")
print(employee_df["Gender"].value_counts())

print("\nDepartment Distribution")
print(employee_df["Department"].value_counts())

print("\nAge Group Distribution")
print(employee_df["AgeGroup"].value_counts())

print("\nSalary Slab Distribution")
print(employee_df["SalarySlab"].value_counts())

print("\nAttrition Distribution")
print(employee_df["Attrition"].value_counts())

print("\nAttrition Rate")

attrition_rate = (
    (employee_df["Attrition"]=="Yes").mean()*100
)

print(round(attrition_rate,2),"%")

============================================================
HR DATASET VALIDATION
============================================================

Total Employees : 2500
Total Columns   : 44

Duplicate Employee Codes : 0
Missing Values :
0

Gender Distribution
Gender
Female    1276
Male      1224
Name: count, dtype: int64

Department Distribution
Department
Marketing          386
Finance            371
Operations         361
Sales              358
Human Resources    358
Administration     337
IT                 329
Name: count, dtype: int64

Age Group Distribution
AgeGroup
26-35    590
46-55    577
36-45    546
18-25    497
55+      290
Name: count, dtype: int64

Salary Slab Distribution
SalarySlab
10+ LPA     1009
3-6 LPA      795
6-10 LPA     601
0-3 LPA       95
Name: count, dtype: int64

Attrition Distribution
Attrition
No     2152
Yes     348
Name: count, dtype: int64

Attrition Rate
13.92 %

In [ ]:
print(generate_salary("IT", "Software Engineer", 1))
print(generate_salary("IT", "Software Engineer", 8))
print(generate_salary("IT", "Software Engineer", 18))

37100
79900
182250

In [ ]:
emp = generate_employee(1)

print(emp["MonthlyIncome"])
print(emp["SalarySlab"])
print(emp["TotalWorkingYears"])
print(emp["JobRole"])

38450
3-6 LPA
0.4
Sales Executive

In [ ]:
employee_df["TotalWorkingYears"].describe()

count    2500.000000
mean        8.727360
std         8.588547
min         0.000000
25%         1.600000
50%         5.900000
75%        13.825000
max        37.700000
Name: TotalWorkingYears, dtype: float64

In [ ]:
employee_df["TotalWorkingYears"].value_counts(bins=6).sort_index()

(-0.0387, 6.283]    1292
(6.283, 12.567]      517
(12.567, 18.85]      316
(18.85, 25.133]      224
(25.133, 31.417]     109
(31.417, 37.7]        42
Name: count, dtype: int64

In [ ]:
employee_df["TotalWorkingYears"].describe()

count    2500.000000
mean        8.727360
std         8.588547
min         0.000000
25%         1.600000
50%         5.900000
75%        13.825000
max        37.700000
Name: TotalWorkingYears, dtype: float64

In [ ]:
employee_df["TotalWorkingYears"].value_counts(bins=6).sort_index()

(-0.0387, 6.283]    1292
(6.283, 12.567]      517
(12.567, 18.85]      316
(18.85, 25.133]      224
(25.133, 31.417]     109
(31.417, 37.7]        42
Name: count, dtype: int64

In [ ]:
employee_df["MonthlyIncome"].describe()

count      2500.000000
mean      83155.540000
std       50098.330745
min       18200.000000
25%       39825.000000
50%       69525.000000
75%      122062.500000
max      240850.000000
Name: MonthlyIncome, dtype: float64

In [ ]:
employee_df.to_csv("HR_Employee_Master.csv", index=False)

print("Dataset Exported Successfully")

Dataset Exported Successfully

In [ ]:
employee_df.head()

,EmployeeCode,Gender,EmployeeName,OfficialEmail,Username,EmployeeCount,Over18,StandardHours,Company,Industry,...,PerformanceRating,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,TrainingTimesLastYear,NumCompaniesWorked,PromotionLast5Years,OverTime,Attrition
0,HRA240001,Female,Harini Bose,harini.bose@hrhub.co.in,harini.bose,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,4,2,3,4,1,5,5.5,No,No,Yes
1,HRA240002,Female,Ritika Shah,ritika.shah@hrhub.co.in,ritika.shah,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,1,1,1,3,1,2,2.6,No,No,No
2,HRA240003,Female,Aditi Gupta,aditi.gupta@hrhub.co.in,aditi.gupta,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,4,1,2,3,4,3,6.0,No,Yes,Yes
3,HRA240004,Female,Sneha Patel,sneha.patel@hrhub.co.in,sneha.patel,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,3,4,3,4,1,1,0.0,No,No,No
4,HRA240005,Male,Harsh Jain,harsh.jain@hrhub.co.in,harsh.jain,1,Y,80,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,2,2,3,3,4,2,0.7,No,Yes,No

In [ ]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeCode              2500 non-null   object
 1   Gender                    2500 non-null   object
 2   EmployeeName              2500 non-null   object
 3   OfficialEmail             2500 non-null   object
 4   Username                  2500 non-null   object
 5   EmployeeCount             2500 non-null   int64
 6   Over18                    2500 non-null   object
 7   StandardHours             2500 non-null   int64
 8   Company                   2500 non-null   object
 9   Industry                  2500 non-null   object
 10  Country                   2500 non-null   object
 11  Age                       2500 non-null   int64
 12  AgeGroup                  2500 non-null   object
 13  DateOfBirth               2500 non-null   object
 14  MaritalStatus             2500 non-null   object
 15  Education                 2500 non-null   object
 16  EducationField            2500 non-null   object
 17  State                     2500 non-null   object
 18  City                      2500 non-null   object
 19  PhoneNumber               2500 non-null   object
 20  Department                2500 non-null   object
 21  JobRole                   2500 non-null   object
 22  BusinessTravel            2500 non-null   object
 23  WorkMode                  2500 non-null   object
 24  TotalWorkingYears         2500 non-null   float64
 25  YearsAtCompany            2500 non-null   int64
 26  YearsInCurrentRole        2500 non-null   int64
 27  YearsSinceLastPromotion   2500 non-null   int64
 28  YearsWithCurrManager      2500 non-null   int64
 29  HireDate                  2500 non-null   object
 30  MonthlyIncome             2500 non-null   int64
 31  SalarySlab                2500 non-null   object
 32  SalaryHikePercent         2500 non-null   int64
 33  StockOptionLevel          2500 non-null   int64
 34  PerformanceRating         2500 non-null   int64
 35  JobSatisfaction           2500 non-null   int64
 36  EnvironmentSatisfaction   2500 non-null   int64
 37  RelationshipSatisfaction  2500 non-null   int64
 38  WorkLifeBalance           2500 non-null   int64
 39  TrainingTimesLastYear     2500 non-null   int64
 40  NumCompaniesWorked        2500 non-null   float64
 41  PromotionLast5Years       2500 non-null   object
 42  OverTime                  2500 non-null   object
 43  Attrition                 2500 non-null   object
dtypes: float64(2), int64(16), object(26)
memory usage: 859.5+ KB

In [ ]:
employee_df.describe(include="all")

,EmployeeCode,Gender,EmployeeName,OfficialEmail,Username,EmployeeCount,Over18,StandardHours,Company,Industry,...,PerformanceRating,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,TrainingTimesLastYear,NumCompaniesWorked,PromotionLast5Years,OverTime,Attrition
count,2500,2500,2500,2500,2500,2500.0,2500,2500.0,2500,2500,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.00000,2500.000000,2500,2500,2500
unique,2500,2,1117,1117,1117,NaN,1,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2
top,HRA242500,Female,Pooja Singh,pooja.singh@hrhub.co.in,pooja.singh,NaN,Y,NaN,HRHub Solutions Pvt. Ltd.,Information Technology & Business Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No
freq,1,1276,8,8,8,NaN,2500,NaN,2500,2500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2048,1774,2152
mean,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,2.934800,2.490000,2.494000,2.485600,2.460000,3.03520,3.300040,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,...,0.758142,1.111393,1.124664,1.131682,1.130359,1.99428,2.959832,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,3.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.800000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,3.000000,3.000000,2.000000,2.000000,2.000000,3.00000,2.900000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,3.000000,3.000000,4.000000,4.000000,3.000000,5.00000,5.225000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,1.0,NaN,80.0,NaN,NaN,...,4.000000,4.000000,4.000000,4.000000,4.000000,6.00000,10.000000,NaN,NaN,NaN